version: '3.8'
services:
  web: &web
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - dev
    restart: unless-stopped
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev
    restart: on-failure
  
  celery-worker:
    <<: *web
    command: celery -A app.celery worker --loglevel=${LOG_LEVEL}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - dev
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - CELERY_RDB_PORT=6900
      - CELERY_RDB_HOST=localhost

networks:
  dev:
    driver: bridge

volumes:
  pgdata:
  redisdata: