# Generated by Django 5.0.6 on 2024-05-29 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tx', models.CharField(max_length=255)),
                ('parent_tx', models.CharField(max_length=255)),
                ('state_root', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('difficulty', models.DecimalField(decimal_places=10, max_digits=20)),
                ('miner', models.CharField(max_length=255)),
                ('reward', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=20)),
                ('extra_data', models.TextField()),
                ('gas_limit', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('nonce', models.CharField(max_length=255)),
                ('sha3_uncles', models.CharField(max_length=255)),
                ('total_difficulty', models.DecimalField(decimal_places=10, max_digits=20)),
                ('transactions', models.IntegerField()),
                ('uncles', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ConfigNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('network', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('ws', 'WebSocket')], default='http', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'unique_together': {('kind', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blockchain.rule')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigMonitorBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.confignode')),
                ('rules', models.ManyToManyField(to='blockchain.rule')),
            ],
            options={
                'verbose_name': 'Monitor Block',
                'verbose_name_plural': 'Monitor Blocks',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tx', models.CharField(max_length=255)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('gas', models.IntegerField()),
                ('gas_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('input', models.TextField()),
                ('nonce', models.IntegerField()),
                ('transaction_index', models.IntegerField()),
                ('v', models.CharField(max_length=255)),
                ('r', models.CharField(max_length=255)),
                ('s', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
