# Generated by Django 5.0.6 on 2024-06-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blockchain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blockchain.confignode'),
        ),
        migrations.AddField(
            model_name='configmonitorblock',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='blockchain.block'),
        ),
    ]
