# Generated by Django 5.0.6 on 2024-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_block_blockchain_configmonitorblock_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='logs_bloom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='receipts_root',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
