# Generated by Django 5.0.6 on 2024-06-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_block_logs_bloom_block_receipts_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='confignode',
            name='chain_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confignode',
            name='network_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confignode',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
